# Generated by Django 3.2 on 2021-04-09 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='geust_can_pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=1, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='votes_to_skip',
            field=models.IntegerField(default=1),
        ),
    ]
