# Generated by Django 3.2 on 2021-04-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='geust_can_pause',
            new_name='guest_can_pause',
        ),
    ]
